using System;
using System.Collections.Generic;

namespace WebAPITandemMixer.Models
{
    public partial class DownloadedCompoundPhase
    {
        public long Id { get; set; }
        public int PhaseNumber { get; set; }
        public bool? PhaseWeighBeltSlabRubber1SkipStep { get; set; }
        public int? PhaseWeighBeltSlabRubber1MaterialBinSource { get; set; }
        public float? PhaseWeighBeltSlabRubber1TargetWeight { get; set; }
        public float? PhaseWeighBeltSlabRubber1WeightPlusTol { get; set; }
        public float? PhaseWeighBeltSlabRubber1WeightMinusTol { get; set; }
        public string? PhaseWeighBeltSlabRubber1MaterialType { get; set; }
        public bool? PhaseWeighBeltSlabRubber2SkipStep { get; set; }
        public int? PhaseWeighBeltSlabRubber2MaterialBinSource { get; set; }
        public float? PhaseWeighBeltSlabRubber2TargetWeight { get; set; }
        public float? PhaseWeighBeltSlabRubber2WeightPlusTol { get; set; }
        public float? PhaseWeighBeltSlabRubber2WeightMinusTol { get; set; }
        public string? PhaseWeighBeltSlabRubber2MaterialType { get; set; }
        public bool? PhaseWeighBeltBaleRubber1SkipStep { get; set; }
        public int? PhaseWeighBeltBaleRubber1MaterialBinSource { get; set; }
        public float? PhaseWeighBeltBaleRubber1TargetWeight { get; set; }
        public float? PhaseWeighBeltBaleRubber1WeightPlusTol { get; set; }
        public float? PhaseWeighBeltBaleRubber1WeightMinusTol { get; set; }
        public string? PhaseWeighBeltBaleRubber1MaterialType { get; set; }
        public bool? PhaseWeighBeltBaleRubber2SkipStep { get; set; }
        public int? PhaseWeighBeltBaleRubber2MaterialBinSource { get; set; }
        public float? PhaseWeighBeltBaleRubber2TargetWeight { get; set; }
        public float? PhaseWeighBeltBaleRubber2WeightPlusTol { get; set; }
        public float? PhaseWeighBeltBaleRubber2WeightMinusTol { get; set; }
        public string? PhaseWeighBeltBaleRubber2MaterialType { get; set; }
        public bool? PhaseWeighBeltBaleRubber3SkipStep { get; set; }
        public int? PhaseWeighBeltBaleRubber3MaterialBinSource { get; set; }
        public float? PhaseWeighBeltBaleRubber3TargetWeight { get; set; }
        public float? PhaseWeighBeltBaleRubber3WeightPlusTol { get; set; }
        public float? PhaseWeighBeltBaleRubber3WeightMinusTol { get; set; }
        public string? PhaseWeighBeltBaleRubber3MaterialType { get; set; }
        public bool? PhaseWeighBeltBaleRubber4SkipStep { get; set; }
        public int? PhaseWeighBeltBaleRubber4MaterialBinSource { get; set; }
        public float? PhaseWeighBeltBaleRubber4TargetWeight { get; set; }
        public float? PhaseWeighBeltBaleRubber4WeightPlusTol { get; set; }
        public float? PhaseWeighBeltBaleRubber4WeightMinusTol { get; set; }
        public string? PhaseWeighBeltBaleRubber4MaterialType { get; set; }
        public bool? PhaseWeighBeltPack1SkipStep { get; set; }
        public int? PhaseWeighBeltPack1MaterialBinSource { get; set; }
        public float? PhaseWeighBeltPack1TargetWeight { get; set; }
        public float? PhaseWeighBeltPack1WeightPlusTol { get; set; }
        public float? PhaseWeighBeltPack1WeightMinusTol { get; set; }
        public string? PhaseWeighBeltPack1MaterialType { get; set; }
        public bool? PhaseWeighBeltPack2SkipStep { get; set; }
        public int? PhaseWeighBeltPack2MaterialBinSource { get; set; }
        public float? PhaseWeighBeltPack2TargetWeight { get; set; }
        public float? PhaseWeighBeltPack2WeightPlusTol { get; set; }
        public float? PhaseWeighBeltPack2WeightMinusTol { get; set; }
        public string? PhaseWeighBeltPack2MaterialType { get; set; }
        public bool? PhaseWeighBeltPack3SkipStep { get; set; }
        public int? PhaseWeighBeltPack3MaterialBinSource { get; set; }
        public float? PhaseWeighBeltPack3TargetWeight { get; set; }
        public float? PhaseWeighBeltPack3WeightPlusTol { get; set; }
        public float? PhaseWeighBeltPack3WeightMinusTol { get; set; }
        public string? PhaseWeighBeltPack3MaterialType { get; set; }
        public bool? PhaseWeighBeltTmaSkipStep { get; set; }
        public int? PhaseWeighBeltTmaMaterialBinSource { get; set; }
        public float? PhaseWeighBeltTmaTargetWeight { get; set; }
        public float? PhaseWeighBeltTmaWeightPlusTol { get; set; }
        public float? PhaseWeighBeltTmaWeightMinusTol { get; set; }
        public string? PhaseWeighBeltTmaMaterialType { get; set; }
        public bool? PhaseWeighBeltPitch1SkipStep { get; set; }
        public int? PhaseWeighBeltPitch1MaterialBinSource { get; set; }
        public float? PhaseWeighBeltPitch1TargetWeight { get; set; }
        public float? PhaseWeighBeltPitch1WeightPlusTol { get; set; }
        public float? PhaseWeighBeltPitch1WeightMinusTol { get; set; }
        public string? PhaseWeighBeltPitch1MaterialType { get; set; }
        public bool? PhaseWeighBeltPitch2SkipStep { get; set; }
        public int? PhaseWeighBeltPitch2MaterialBinSource { get; set; }
        public float? PhaseWeighBeltPitch2TargetWeight { get; set; }
        public float? PhaseWeighBeltPitch2WeightPlusTol { get; set; }
        public float? PhaseWeighBeltPitch2WeightMinusTol { get; set; }
        public string? PhaseWeighBeltPitch2MaterialType { get; set; }
        public bool? PhaseChargeBeltPitchPack1SkipStep { get; set; }
        public int? PhaseChargeBeltPitchPack1MaterialBinSource { get; set; }
        public float? PhaseChargeBeltPitchPack1TargetWeight { get; set; }
        public float? PhaseChargeBeltPitchPack1WeightPlusTol { get; set; }
        public float? PhaseChargeBeltPitchPack1WeightMinusTol { get; set; }
        public string? PhaseChargeBeltPitchPack1MaterialType { get; set; }
        public bool? PhaseChargeBeltPitchPack2SkipStep { get; set; }
        public int? PhaseChargeBeltPitchPack2MaterialBinSource { get; set; }
        public float? PhaseChargeBeltPitchPack2TargetWeight { get; set; }
        public float? PhaseChargeBeltPitchPack2WeightPlusTol { get; set; }
        public float? PhaseChargeBeltPitchPack2WeightMinusTol { get; set; }
        public string? PhaseChargeBeltPitchPack2MaterialType { get; set; }
        public bool? PhaseChargeBeltPitchPack3SkipStep { get; set; }
        public int? PhaseChargeBeltPitchPack3MaterialBinSource { get; set; }
        public float? PhaseChargeBeltPitchPack3TargetWeight { get; set; }
        public float? PhaseChargeBeltPitchPack3WeightPlusTol { get; set; }
        public float? PhaseChargeBeltPitchPack3WeightMinusTol { get; set; }
        public string? PhaseChargeBeltPitchPack3MaterialType { get; set; }
        public bool? PhaseChargeBeltPitchPack4SkipStep { get; set; }
        public int? PhaseChargeBeltPitchPack4MaterialBinSource { get; set; }
        public float? PhaseChargeBeltPitchPack4TargetWeight { get; set; }
        public float? PhaseChargeBeltPitchPack4WeightPlusTol { get; set; }
        public float? PhaseChargeBeltPitchPack4WeightMinusTol { get; set; }
        public string? PhaseChargeBeltPitchPack4MaterialType { get; set; }
        public bool? PhaseChargeBeltPitchPack5SkipStep { get; set; }
        public int? PhaseChargeBeltPitchPack5MaterialBinSource { get; set; }
        public float? PhaseChargeBeltPitchPack5TargetWeight { get; set; }
        public float? PhaseChargeBeltPitchPack5WeightPlusTol { get; set; }
        public float? PhaseChargeBeltPitchPack5WeightMinusTol { get; set; }
        public string? PhaseChargeBeltPitchPack5MaterialType { get; set; }
        public string? PhaseTopMixerPhaseType { get; set; }
        public int? PhaseTopMixerGateDwell { get; set; }
        public int? PhaseTopMixerMinPhaseTime { get; set; }
        public int? PhaseTopMixerMaxPhaseTime { get; set; }
        public float? PhaseTopMixerMaxPhaseTemp { get; set; }
        public float? PhaseTopMixerMaxPhaseKwh { get; set; }
        public string? PhaseTopMixerPhaseDescription { get; set; }
        public bool? PhaseTopMixerCarbonBlack0SkipStep { get; set; }
        public int? PhaseTopMixerCarbonBlack0MaterialBinSource { get; set; }
        public float? PhaseTopMixerCarbonBlack0TargetWeight { get; set; }
        public float? PhaseTopMixerCarbonBlack0WeightPlusTol { get; set; }
        public float? PhaseTopMixerCarbonBlack0WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCarbonBlack0TimingType { get; set; }
        public float? PhaseTopMixerCarbonBlack0TimingValue { get; set; }
        public string? PhaseTopMixerCarbonBlack0MaterialType { get; set; }
        public bool? PhaseTopMixerCarbonBlack1SkipStep { get; set; }
        public int? PhaseTopMixerCarbonBlack1MaterialBinSource { get; set; }
        public float? PhaseTopMixerCarbonBlack1TargetWeight { get; set; }
        public float? PhaseTopMixerCarbonBlack1WeightPlusTol { get; set; }
        public float? PhaseTopMixerCarbonBlack1WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCarbonBlack1TimingType { get; set; }
        public float? PhaseTopMixerCarbonBlack1TimingValue { get; set; }
        public string? PhaseTopMixerCarbonBlack1MaterialType { get; set; }
        public bool? PhaseTopMixerCarbonBlack2SkipStep { get; set; }
        public int? PhaseTopMixerCarbonBlack2MaterialBinSource { get; set; }
        public float? PhaseTopMixerCarbonBlack2TargetWeight { get; set; }
        public float? PhaseTopMixerCarbonBlack2WeightPlusTol { get; set; }
        public float? PhaseTopMixerCarbonBlack2WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCarbonBlack2TimingType { get; set; }
        public float? PhaseTopMixerCarbonBlack2TimingValue { get; set; }
        public string? PhaseTopMixerCarbonBlack2MaterialType { get; set; }
        public bool? PhaseTopMixerCarbonBlack3SkipStep { get; set; }
        public int? PhaseTopMixerCarbonBlack3MaterialBinSource { get; set; }
        public float? PhaseTopMixerCarbonBlack3TargetWeight { get; set; }
        public float? PhaseTopMixerCarbonBlack3WeightPlusTol { get; set; }
        public float? PhaseTopMixerCarbonBlack3WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCarbonBlack3TimingType { get; set; }
        public float? PhaseTopMixerCarbonBlack3TimingValue { get; set; }
        public string? PhaseTopMixerCarbonBlack3MaterialType { get; set; }
        public bool? PhaseTopMixerCarbonBlack4SkipStep { get; set; }
        public int? PhaseTopMixerCarbonBlack4MaterialBinSource { get; set; }
        public float? PhaseTopMixerCarbonBlack4TargetWeight { get; set; }
        public float? PhaseTopMixerCarbonBlack4WeightPlusTol { get; set; }
        public float? PhaseTopMixerCarbonBlack4WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCarbonBlack4TimingType { get; set; }
        public float? PhaseTopMixerCarbonBlack4TimingValue { get; set; }
        public string? PhaseTopMixerCarbonBlack4MaterialType { get; set; }
        public bool? PhaseTopMixerPigment0SkipStep { get; set; }
        public int? PhaseTopMixerPigment0MaterialBinSource { get; set; }
        public float? PhaseTopMixerPigment0TargetWeight { get; set; }
        public float? PhaseTopMixerPigment0WeightPlusTol { get; set; }
        public float? PhaseTopMixerPigment0WeightMinusTol { get; set; }
        public byte? PhaseTopMixerPigment0TimingType { get; set; }
        public float? PhaseTopMixerPigment0TimingValue { get; set; }
        public string? PhaseTopMixerPigment0MaterialType { get; set; }
        public bool? PhaseTopMixerPigment1SkipStep { get; set; }
        public int? PhaseTopMixerPigment1MaterialBinSource { get; set; }
        public float? PhaseTopMixerPigment1TargetWeight { get; set; }
        public float? PhaseTopMixerPigment1WeightPlusTol { get; set; }
        public float? PhaseTopMixerPigment1WeightMinusTol { get; set; }
        public byte? PhaseTopMixerPigment1TimingType { get; set; }
        public float? PhaseTopMixerPigment1TimingValue { get; set; }
        public string? PhaseTopMixerPigment1MaterialType { get; set; }
        public bool? PhaseTopMixerPigment2SkipStep { get; set; }
        public int? PhaseTopMixerPigment2MaterialBinSource { get; set; }
        public float? PhaseTopMixerPigment2TargetWeight { get; set; }
        public float? PhaseTopMixerPigment2WeightPlusTol { get; set; }
        public float? PhaseTopMixerPigment2WeightMinusTol { get; set; }
        public byte? PhaseTopMixerPigment2TimingType { get; set; }
        public float? PhaseTopMixerPigment2TimingValue { get; set; }
        public string? PhaseTopMixerPigment2MaterialType { get; set; }
        public bool? PhaseTopMixerPigment3SkipStep { get; set; }
        public int? PhaseTopMixerPigment3MaterialBinSource { get; set; }
        public float? PhaseTopMixerPigment3TargetWeight { get; set; }
        public float? PhaseTopMixerPigment3WeightPlusTol { get; set; }
        public float? PhaseTopMixerPigment3WeightMinusTol { get; set; }
        public byte? PhaseTopMixerPigment3TimingType { get; set; }
        public float? PhaseTopMixerPigment3TimingValue { get; set; }
        public string? PhaseTopMixerPigment3MaterialType { get; set; }
        public bool? PhaseTopMixerPigment4SkipStep { get; set; }
        public int? PhaseTopMixerPigment4MaterialBinSource { get; set; }
        public float? PhaseTopMixerPigment4TargetWeight { get; set; }
        public float? PhaseTopMixerPigment4WeightPlusTol { get; set; }
        public float? PhaseTopMixerPigment4WeightMinusTol { get; set; }
        public byte? PhaseTopMixerPigment4TimingType { get; set; }
        public float? PhaseTopMixerPigment4TimingValue { get; set; }
        public string? PhaseTopMixerPigment4MaterialType { get; set; }
        public bool? PhaseTopMixerCanDump0SkipStep { get; set; }
        public int? PhaseTopMixerCanDump0MaterialBinSource { get; set; }
        public float? PhaseTopMixerCanDump0TargetWeight { get; set; }
        public float? PhaseTopMixerCanDump0WeightPlusTol { get; set; }
        public float? PhaseTopMixerCanDump0WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCanDump0TimingType { get; set; }
        public float? PhaseTopMixerCanDump0TimingValue { get; set; }
        public string? PhaseTopMixerCanDump0MaterialType { get; set; }
        public bool? PhaseTopMixerCanDump1SkipStep { get; set; }
        public int? PhaseTopMixerCanDump1MaterialBinSource { get; set; }
        public float? PhaseTopMixerCanDump1TargetWeight { get; set; }
        public float? PhaseTopMixerCanDump1WeightPlusTol { get; set; }
        public float? PhaseTopMixerCanDump1WeightMinusTol { get; set; }
        public byte? PhaseTopMixerCanDump1TimingType { get; set; }
        public float? PhaseTopMixerCanDump1TimingValue { get; set; }
        public string? PhaseTopMixerCanDump1MaterialType { get; set; }
        public bool? PhaseTopMixerOil0SkipStep { get; set; }
        public int? PhaseTopMixerOil0MaterialBinSource { get; set; }
        public float? PhaseTopMixerOil0TargetWeight { get; set; }
        public float? PhaseTopMixerOil0WeightPlusTol { get; set; }
        public float? PhaseTopMixerOil0WeightMinusTol { get; set; }
        public byte? PhaseTopMixerOil0TimingType { get; set; }
        public float? PhaseTopMixerOil0TimingValue { get; set; }
        public string? PhaseTopMixerOil0MaterialType { get; set; }
        public bool? PhaseTopMixerOil1SkipStep { get; set; }
        public int? PhaseTopMixerOil1MaterialBinSource { get; set; }
        public float? PhaseTopMixerOil1TargetWeight { get; set; }
        public float? PhaseTopMixerOil1WeightPlusTol { get; set; }
        public float? PhaseTopMixerOil1WeightMinusTol { get; set; }
        public byte? PhaseTopMixerOil1TimingType { get; set; }
        public float? PhaseTopMixerOil1TimingValue { get; set; }
        public string? PhaseTopMixerOil1MaterialType { get; set; }
        public bool? PhaseTopMixerOil2SkipStep { get; set; }
        public int? PhaseTopMixerOil2MaterialBinSource { get; set; }
        public float? PhaseTopMixerOil2TargetWeight { get; set; }
        public float? PhaseTopMixerOil2WeightPlusTol { get; set; }
        public float? PhaseTopMixerOil2WeightMinusTol { get; set; }
        public byte? PhaseTopMixerOil2TimingType { get; set; }
        public float? PhaseTopMixerOil2TimingValue { get; set; }
        public string? PhaseTopMixerOil2MaterialType { get; set; }
        public bool? PhaseTopMixerOil3SkipStep { get; set; }
        public int? PhaseTopMixerOil3MaterialBinSource { get; set; }
        public float? PhaseTopMixerOil3TargetWeight { get; set; }
        public float? PhaseTopMixerOil3WeightPlusTol { get; set; }
        public float? PhaseTopMixerOil3WeightMinusTol { get; set; }
        public byte? PhaseTopMixerOil3TimingType { get; set; }
        public float? PhaseTopMixerOil3TimingValue { get; set; }
        public string? PhaseTopMixerOil3MaterialType { get; set; }
        public bool? PhaseTopMixerOil4SkipStep { get; set; }
        public int? PhaseTopMixerOil4MaterialBinSource { get; set; }
        public float? PhaseTopMixerOil4TargetWeight { get; set; }
        public float? PhaseTopMixerOil4WeightPlusTol { get; set; }
        public float? PhaseTopMixerOil4WeightMinusTol { get; set; }
        public byte? PhaseTopMixerOil4TimingType { get; set; }
        public float? PhaseTopMixerOil4TimingValue { get; set; }
        public string? PhaseTopMixerOil4MaterialType { get; set; }
        public float? PhaseTopMixerRamControl0RamPostion { get; set; }
        public float? PhaseTopMixerRamControl0RamPressure { get; set; }
        public byte? PhaseTopMixerRamControl0TimingType { get; set; }
        public float? PhaseTopMixerRamControl0TimingValue { get; set; }
        public float? PhaseTopMixerRamControl1RamPostion { get; set; }
        public float? PhaseTopMixerRamControl1RamPressure { get; set; }
        public byte? PhaseTopMixerRamControl1TimingType { get; set; }
        public float? PhaseTopMixerRamControl1TimingValue { get; set; }
        public float? PhaseTopMixerRamControl2RamPostion { get; set; }
        public float? PhaseTopMixerRamControl2RamPressure { get; set; }
        public byte? PhaseTopMixerRamControl2TimingType { get; set; }
        public float? PhaseTopMixerRamControl2TimingValue { get; set; }
        public float? PhaseTopMixerRamControl3RamPostion { get; set; }
        public float? PhaseTopMixerRamControl3RamPressure { get; set; }
        public byte? PhaseTopMixerRamControl3TimingType { get; set; }
        public float? PhaseTopMixerRamControl3TimingValue { get; set; }
        public float? PhaseTopMixerRamControl4RamPostion { get; set; }
        public float? PhaseTopMixerRamControl4RamPressure { get; set; }
        public byte? PhaseTopMixerRamControl4TimingType { get; set; }
        public float? PhaseTopMixerRamControl4TimingValue { get; set; }
        public float? PhaseTopMixerMixerSpeed0MixerSpeed { get; set; }
        public byte? PhaseTopMixerMixerSpeed0TimingType { get; set; }
        public float? PhaseTopMixerMixerSpeed0TimingValue { get; set; }
        public float? PhaseTopMixerMixerSpeed1MixerSpeed { get; set; }
        public byte? PhaseTopMixerMixerSpeed1TimingType { get; set; }
        public float? PhaseTopMixerMixerSpeed1TimingValue { get; set; }
        public float? PhaseTopMixerMixerSpeed2MixerSpeed { get; set; }
        public byte? PhaseTopMixerMixerSpeed2TimingType { get; set; }
        public float? PhaseTopMixerMixerSpeed2TimingValue { get; set; }
        public float? PhaseTopMixerMixerSpeed3MixerSpeed { get; set; }
        public byte? PhaseTopMixerMixerSpeed3TimingType { get; set; }
        public float? PhaseTopMixerMixerSpeed3TimingValue { get; set; }
        public float? PhaseTopMixerMixerSpeed4MixerSpeed { get; set; }
        public byte? PhaseTopMixerMixerSpeed4TimingType { get; set; }
        public float? PhaseTopMixerMixerSpeed4TimingValue { get; set; }
        public byte? PhaseTopMixerPhaseTransition0Variable { get; set; }
        public float? PhaseTopMixerPhaseTransition0Value { get; set; }
        public byte? PhaseTopMixerPhaseTransition1Variable { get; set; }
        public float? PhaseTopMixerPhaseTransition1Value { get; set; }
        public byte? PhaseTopMixerPhaseTransition2Variable { get; set; }
        public float? PhaseTopMixerPhaseTransition2Value { get; set; }
        public byte? PhaseTopMixerPhaseCheck0Variable { get; set; }
        public float? PhaseTopMixerPhaseCheck0CheckTime { get; set; }
        public float? PhaseTopMixerPhaseCheck0Min { get; set; }
        public float? PhaseTopMixerPhaseCheck0Max { get; set; }
        public byte? PhaseTopMixerPhaseCheck1Variable { get; set; }
        public float? PhaseTopMixerPhaseCheck1CheckTime { get; set; }
        public float? PhaseTopMixerPhaseCheck1Min { get; set; }
        public float? PhaseTopMixerPhaseCheck1Max { get; set; }
        public byte? PhaseTopMixerPhaseCheck2Variable { get; set; }
        public float? PhaseTopMixerPhaseCheck2CheckTime { get; set; }
        public float? PhaseTopMixerPhaseCheck2Min { get; set; }
        public float? PhaseTopMixerPhaseCheck2Max { get; set; }
        public string? PhaseBotMixerPhaseType { get; set; }
        public int? PhaseBotMixerGateDwell { get; set; }
        public int? PhaseBotMixerMinPhaseTime { get; set; }
        public int? PhaseBotMixerMaxPhaseTime { get; set; }
        public float? PhaseBotMixerMaxPhaseTemp { get; set; }
        public float? PhaseBotMixerMaxPhaseKwh { get; set; }
        public string? PhaseBotMixerPhaseDescription { get; set; }
        public bool? PhaseBotMixerChuteSkipStep { get; set; }
        public int? PhaseBotMixerChuteMaterialBinSource { get; set; }
        public float? PhaseBotMixerChuteTargetWeight { get; set; }
        public float? PhaseBotMixerChuteWeightPlusTol { get; set; }
        public float? PhaseBotMixerChuteWeightMinusTol { get; set; }
        public byte? PhaseBotMixerChuteTimingType { get; set; }
        public float? PhaseBotMixerChuteTimingValue { get; set; }
        public string? PhaseBotMixerChuteMaterialType { get; set; }
        public byte? PhaseBotMixerPusherControl0TimingType { get; set; }
        public float? PhaseBotMixerPusherControl0TimingValue { get; set; }
        public byte? PhaseBotMixerPusherControl1TimingType { get; set; }
        public float? PhaseBotMixerPusherControl1TimingValue { get; set; }
        public byte? PhaseBotMixerPusherControl2TimingType { get; set; }
        public float? PhaseBotMixerPusherControl2TimingValue { get; set; }
        public byte? PhaseBotMixerPusherControl3TimingType { get; set; }
        public float? PhaseBotMixerPusherControl3TimingValue { get; set; }
        public byte? PhaseBotMixerPusherControl4TimingType { get; set; }
        public float? PhaseBotMixerPusherControl4TimingValue { get; set; }
        public float? PhaseBotMixerMixerSpeed0MixerSpeed { get; set; }
        public byte? PhaseBotMixerMixerSpeed0TimingType { get; set; }
        public float? PhaseBotMixerMixerSpeed0TimingValue { get; set; }
        public float? PhaseBotMixerMixerSpeed1MixerSpeed { get; set; }
        public byte? PhaseBotMixerMixerSpeed1TimingType { get; set; }
        public float? PhaseBotMixerMixerSpeed1TimingValue { get; set; }
        public float? PhaseBotMixerMixerSpeed2MixerSpeed { get; set; }
        public byte? PhaseBotMixerMixerSpeed2TimingType { get; set; }
        public float? PhaseBotMixerMixerSpeed2TimingValue { get; set; }
        public float? PhaseBotMixerMixerSpeed3MixerSpeed { get; set; }
        public byte? PhaseBotMixerMixerSpeed3TimingType { get; set; }
        public float? PhaseBotMixerMixerSpeed3TimingValue { get; set; }
        public float? PhaseBotMixerMixerSpeed4MixerSpeed { get; set; }
        public byte? PhaseBotMixerMixerSpeed4TimingType { get; set; }
        public float? PhaseBotMixerMixerSpeed4TimingValue { get; set; }
        public byte? PhaseBotMixerPhaseTransition0Variable { get; set; }
        public float? PhaseBotMixerPhaseTransition0Value { get; set; }
        public byte? PhaseBotMixerPhaseTransition1Variable { get; set; }
        public float? PhaseBotMixerPhaseTransition1Value { get; set; }
        public byte? PhaseBotMixerPhaseTransition2Variable { get; set; }
        public float? PhaseBotMixerPhaseTransition2Value { get; set; }
        public byte? PhaseBotMixerPhaseCheck0Variable { get; set; }
        public float? PhaseBotMixerPhaseCheck0CheckTime { get; set; }
        public float? PhaseBotMixerPhaseCheck0Min { get; set; }
        public float? PhaseBotMixerPhaseCheck0Max { get; set; }
        public byte? PhaseBotMixerPhaseCheck1Variable { get; set; }
        public float? PhaseBotMixerPhaseCheck1CheckTime { get; set; }
        public float? PhaseBotMixerPhaseCheck1Min { get; set; }
        public float? PhaseBotMixerPhaseCheck1Max { get; set; }
        public byte? PhaseBotMixerPhaseCheck2Variable { get; set; }
        public float? PhaseBotMixerPhaseCheck2CheckTime { get; set; }
        public float? PhaseBotMixerPhaseCheck2Min { get; set; }
        public float? PhaseBotMixerPhaseCheck2Max { get; set; }
    }
}
