using System;
using System.Collections.Generic;

namespace WebAPITandemMixer.Models
{
    public partial class DownloadedCompoundPhasesTop
    {
        public long Id { get; set; }
        public int PhaseNumber { get; set; }
        public short? TopMixerPhasePhaseType { get; set; }
        public string? TopMixerPhasePhaseDescription { get; set; }
        public int? TopMixerPhaseMixParametersGateDwell { get; set; }
        public int? TopMixerPhaseMixParametersMinPhaseTime { get; set; }
        public int? TopMixerPhaseMixParametersMaxPhaseTime { get; set; }
        public float? TopMixerPhaseMixParametersMaxPhaseTemp { get; set; }
        public float? TopMixerPhaseMixParametersMaxPhaseKwh { get; set; }
        public float? TopMixerPhaseMixParametersDtctempTarget { get; set; }
        public float? TopMixerPhaseMixParametersDtctempMin { get; set; }
        public float? TopMixerPhaseMixParametersDtctempMax { get; set; }
        public float? TopMixerPhaseMixParametersDtcspeedTarget { get; set; }
        public float? TopMixerPhaseMixParametersDtcspeedMin { get; set; }
        public float? TopMixerPhaseMixParametersDtcspeedMax { get; set; }
        public float? TopMixerPhaseMixParametersRamControl0RamPostion { get; set; }
        public float? TopMixerPhaseMixParametersRamControl0RamPressure { get; set; }
        public short? TopMixerPhaseMixParametersRamControl0TimingType { get; set; }
        public float? TopMixerPhaseMixParametersRamControl0TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersRamControl1RamPostion { get; set; }
        public float? TopMixerPhaseMixParametersRamControl1RamPressure { get; set; }
        public short? TopMixerPhaseMixParametersRamControl1TimingType { get; set; }
        public float? TopMixerPhaseMixParametersRamControl1TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersRamControl2RamPostion { get; set; }
        public float? TopMixerPhaseMixParametersRamControl2RamPressure { get; set; }
        public short? TopMixerPhaseMixParametersRamControl2TimingType { get; set; }
        public float? TopMixerPhaseMixParametersRamControl2TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersRamControl3RamPostion { get; set; }
        public float? TopMixerPhaseMixParametersRamControl3RamPressure { get; set; }
        public short? TopMixerPhaseMixParametersRamControl3TimingType { get; set; }
        public float? TopMixerPhaseMixParametersRamControl3TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersRamControl4RamPostion { get; set; }
        public float? TopMixerPhaseMixParametersRamControl4RamPressure { get; set; }
        public short? TopMixerPhaseMixParametersRamControl4TimingType { get; set; }
        public float? TopMixerPhaseMixParametersRamControl4TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed0MixerSpeed { get; set; }
        public short? TopMixerPhaseMixParametersMixerSpeed0TimingType { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed0TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed1MixerSpeed { get; set; }
        public short? TopMixerPhaseMixParametersMixerSpeed1TimingType { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed1TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed2MixerSpeed { get; set; }
        public short? TopMixerPhaseMixParametersMixerSpeed2TimingType { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed2TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed3MixerSpeed { get; set; }
        public short? TopMixerPhaseMixParametersMixerSpeed3TimingType { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed3TimingValue { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed4MixerSpeed { get; set; }
        public short? TopMixerPhaseMixParametersMixerSpeed4TimingType { get; set; }
        public float? TopMixerPhaseMixParametersMixerSpeed4TimingValue { get; set; }
        public short? TopMixerPhaseMixParametersPhaseTransition0Variable { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition0Value { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition0Duration { get; set; }
        public short? TopMixerPhaseMixParametersPhaseTransition1Variable { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition1Value { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition1Duration { get; set; }
        public short? TopMixerPhaseMixParametersPhaseTransition2Variable { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition2Value { get; set; }
        public float? TopMixerPhaseMixParametersPhaseTransition2Duration { get; set; }
        public short? TopMixerPhaseMixParametersPhaseCheck0Type { get; set; }
        public int? TopMixerPhaseMixParametersPhaseCheck0TriggerTime { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck0Min { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck0Max { get; set; }
        public short? TopMixerPhaseMixParametersPhaseCheck1Type { get; set; }
        public int? TopMixerPhaseMixParametersPhaseCheck1TriggerTime { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck1Min { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck1Max { get; set; }
        public short? TopMixerPhaseMixParametersPhaseCheck2Type { get; set; }
        public int? TopMixerPhaseMixParametersPhaseCheck2TriggerTime { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck2Min { get; set; }
        public float? TopMixerPhaseMixParametersPhaseCheck2Max { get; set; }
        public bool? TopMixerPhaseMixIngredientsCarbonBlack0SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCarbonBlack0MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack0TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack0WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack0WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCarbonBlack0TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack0TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCarbonBlack0MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCarbonBlack1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCarbonBlack1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack1WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCarbonBlack1TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack1TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCarbonBlack1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCarbonBlack2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCarbonBlack2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack2WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCarbonBlack2TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack2TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCarbonBlack2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCarbonBlack3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCarbonBlack3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack3WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCarbonBlack3TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack3TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCarbonBlack3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCarbonBlack4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCarbonBlack4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack4WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCarbonBlack4TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCarbonBlack4TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCarbonBlack4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsPigment0SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsPigment0MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment0TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment0WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment0WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsPigment0TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment0TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsPigment0MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsPigment1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsPigment1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment1WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsPigment1TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment1TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsPigment1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsPigment2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsPigment2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment2WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsPigment2TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment2TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsPigment2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsPigment3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsPigment3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment3WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsPigment3TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment3TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsPigment3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsPigment4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsPigment4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment4WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsPigment4TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsPigment4TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsPigment4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCanDump0SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCanDump0MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump0TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump0WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump0WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCanDump0TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump0TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCanDump0MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsCanDump1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsCanDump1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump1WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsCanDump1TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsCanDump1TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsCanDump1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil0SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil0MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil0TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil0WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil0WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil0TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil0TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil0MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil1WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil1TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil1TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil2WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil2TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil2TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil3WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil3TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil3TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil4WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil4TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil4TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsOil5SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsOil5MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsOil5TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsOil5WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsOil5WeightMinusTol { get; set; }
        public short? TopMixerPhaseMixIngredientsOil5TimingType { get; set; }
        public float? TopMixerPhaseMixIngredientsOil5TimingValue { get; set; }
        public string? TopMixerPhaseMixIngredientsOil5MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltSlabRubber1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltSlabRubber2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltBaleRubber1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltBaleRubber2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltBaleRubber3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltBaleRubber4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack1WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack2WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack3WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack4WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack5SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack5MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack5TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack5WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack5WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack5MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack6SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack6MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack6TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack6WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack6WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack6MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack7SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack7MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack7TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack7WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack7WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack7MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack8SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack8MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack8TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack8WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack8WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack8MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack9SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack9MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack9TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack9WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack9WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack9MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltPitchPack10SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltPitchPack10MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack10TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack10WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltPitchPack10WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltPitchPack10MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsWeighBeltTmaSkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsWeighBeltTmaMaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltTmaTargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltTmaWeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsWeighBeltTmaWeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsWeighBeltTmaMaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsChargeBeltPitchPack1SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsChargeBeltPitchPack1MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack1TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack1WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack1WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsChargeBeltPitchPack1MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsChargeBeltPitchPack2SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsChargeBeltPitchPack2MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack2TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack2WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack2WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsChargeBeltPitchPack2MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsChargeBeltPitchPack3SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsChargeBeltPitchPack3MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack3TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack3WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack3WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsChargeBeltPitchPack3MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsChargeBeltPitchPack4SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsChargeBeltPitchPack4MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack4TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack4WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack4WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsChargeBeltPitchPack4MaterialType { get; set; }
        public bool? TopMixerPhaseMixIngredientsChargeBeltPitchPack5SkipStep { get; set; }
        public int? TopMixerPhaseMixIngredientsChargeBeltPitchPack5MaterialBinSource { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack5TargetWeight { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack5WeightPlusTol { get; set; }
        public float? TopMixerPhaseMixIngredientsChargeBeltPitchPack5WeightMinusTol { get; set; }
        public string? TopMixerPhaseMixIngredientsChargeBeltPitchPack5MaterialType { get; set; }
    }
}
